name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint || echo "No lint configured"
      
      - name: Run tests
        run: npm test || echo "No tests configured"
      
      - name: Build application
        run: ./scripts/build.sh
      
      - name: Build Docker image (verification only)
        run: docker build -t test-image .
