name: Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: ./scripts/build.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: 'gcloud info'

      - name: Build image and push to Artifact Registry
        run: 'gcloud builds submit --tag ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/mailerone-backend-repo/mailerone-backend:latest .'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 35.244.46.62 >> ~/.ssh/known_hosts

        # Deploy to VM via SSH
      - name: SSH into VM and run deploy script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.INSTANCE_PUBLIC_IP }}
          username: tech.sapmenc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment on VM..."
            cd ./scripts
            sudo ./deploy.sh
