services:
  api:
    container_name: mailerone-api
    build: .

    depends_on:
      - db

    env_file:
      - path: .env
        required: true

    ports:
      - 5002:5002

  db:
    container_name: mailerone-db
    image: mongo:8.0
    restart: unless-stopped
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    ports:
      - 27017:27017

    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped

    env_file:
      - path: .env
        required: true

    ports:
      - 8081:8081
      - 4040:4040

    command:
      - 'http'
      - 'api:5002'
      - '--url'
      - 'https://electric-supposedly-honeybee.ngrok-free.app'

    depends_on:
      - api

volumes:
  mongo_config:
  mongo_data:
    driver: local
